export const Cards = [
    {
        id: 1,
        image: require('../assets/tex.jpg'),
        text: 'Textile',
        rating: '7.8',
        read: 'Read More',
        produtInfor: 'Product Information',
        info: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit.  Dolor provident animi beatae nulla, dolorem in quae placeat ab eveniet, illo quidem expedita ut eligendi omnis obcaecati suscipit vitae reiciendis delectus.',
        bidNumber: 'D200',
        bid: 'Place Your Bid',
        minimumBid: 1500,
        confirm: 'Confirm',
    },
    {
        id: 2,
        image: require('../assets/mm.jpg'),
        text: 'Shoes',
        rating: '2.3',
        read: 'Read More',
        produtInfor: 'Product Information',
        info: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit.  Dolor provident animi beatae nulla, dolorem in quae placeat ab eveniet, illo quidem expedita ut eligendi omnis obcaecati suscipit vitae reiciendis delectus.',
        bidNumber: 'D200',
        bid: 'Place Your Bid',
        minimumBid: 1500,
        confirm: 'Confirm',
    },
    {
        id: 3,
        image: require('../assets/hh.jpg'),
        text: 'Hand Bags',
        rating: '1,5',
        read: 'Read More',
        produtInfor: 'Product Information',
        info: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit.  Dolor provident animi beatae nulla, dolorem in quae placeat ab eveniet, illo quidem expedita ut eligendi omnis obcaecati suscipit vitae reiciendis delectus.',
        bidNumber: 'D200',
        bid: 'Place Your Bid',
        minimumBid: 1500,
        confirm: 'Confirm',
    },
    {
        id: 4,
        image: require('../assets/sho.jpg'),
        text: 'Shoes',
        rating: '3',
        read: 'Read More',
        produtInfor: 'Product Information',
        info: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit.  Dolor provident animi beatae nulla, dolorem in quae placeat ab eveniet, illo quidem expedita ut eligendi omnis obcaecati suscipit vitae reiciendis delectus.',
        bidNumber: 'D200',
        bid: 'Place Your Bid',
        minimumBid: 1500,
        confirm: 'Confirm',
    },
    {
        id: 5,
        image: require('../assets/oop.jpg'),
        text: 'Shirts',
        rating: '7',
        read: 'Read More',
        produtInfor: 'Product Information',
        info: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit.  Dolor provident animi beatae nulla, dolorem in quae placeat ab eveniet, illo quidem expedita ut eligendi omnis obcaecati suscipit vitae reiciendis delectus.',
        bidNumber: 'D200',
        bid: 'Place Your Bid',
        minimumBid: 1500,
        confirm: 'Confirm',
    },
    {
        id: 6,
        image: require('../assets/pp.jpg'),
        text: 'Bags',
        rating: '9',
        read: 'Read More',
        produtInfor: 'Product Information',
        info: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit.  Dolor provident animi beatae nulla, dolorem in quae placeat ab eveniet, illo quidem expedita ut eligendi omnis obcaecati suscipit vitae reiciendis delectus.',
        bidNumber: 'D200',
        bid: 'Place Your Bid',
        minimumBid: 1500,
        confirm: 'Confirm',
    }
]